---
title: "DDS_CS2_U15_rmd"
author: "Dawn Bowerman"
date: "11/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}


#Loading librarys, filtering, and checking for missing data

library(class)
library(caret)
library(e1071)
library(tidyverse)
library(scales)
library(ggplot2)





setwd("H:\\Schools\\SMU\\DoingDataScienceHomework\\UnitOne\\Unit One\\Unit 14 and 15 Case Study 2\\DDS_CaseStudy.2_U15")


CaseStudy2-data <- read.csv(file = 'CaseStudy2-data.csv')



CaseStudy2-data %>% filter(!is.na(Attrition)) #Filter out rows with missing data



CS2YesAttrition <- CaseStudy2-data %>% filter(Attrition == "Yes")
view(CS2YesAttrition)





CS2YesAttritselect <- CS2YesAttrition %>% select(Age, DistanceFromHome, EnvironmentSatisfaction, HourlyRate,
JobSatisfaction, Education, DailyRate, JobInvolvement, MonthlyIncome, JobLevel, MonthlyRate, NumCompaniesWorked,
PercentSalaryHike, PerformanceRating, RelationshipSatisfaction, YearsWithCurrManager,WorkLifeBalance, YearsInCurrentRole, YearsAtCompany, StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear, YearsSinceLastPromotion)

view(CS2YesAttritselect)


```





```{r}

# Graphs of the Percent of Yes Attrition by Contributing Character-type Factors



CS2YesAttrition %>% ggplot(mapping = aes(x = OverTime, fill = OverTime)) + geom_bar() + coord_polar() + ggtitle("Polar Bar Chart of OverTime - Yes Attrition Counts")


CS2YesAttrition %>% ggplot(mapping = aes(x = BusinessTravel, fill = BusinessTravel)) + geom_bar() + coord_polar() + ggtitle("Polar Bar Chart of BusinessTravel - Yes Attrition Counts")


CS2YesAttrition %>% ggplot(mapping = aes(x = Department, fill = Department)) + geom_bar() + coord_polar() + ggtitle("Polar Bar Chart of Department - Yes Attrition Counts")


CS2YesAttrition %>% ggplot(mapping = aes(x = EducationField, fill = EducationField)) + geom_bar() + coord_polar() + ggtitle("Polar Bar Chart of EducationField - Yes Attrition Counts")


CS2YesAttrition %>% ggplot(mapping = aes(x = Gender, fill = Gender)) + geom_bar() + coord_polar() + ggtitle("Polar Bar Chart of Gender - Yes Attrition Counts")


CS2YesAttrition %>% ggplot(mapping = aes(x = MaritalStatus, fill = MaritalStatus)) + geom_bar() + coord_polar() + ggtitle("Polar Bar Chart of MaritalStatus - Yes Attrition Counts")



CS2YesAttrition %>% ggplot(mapping = aes(x = JobRole, fill = JobRole)) + geom_bar() + coord_polar() + ggtitle("Polar Bar Chart of Job Role - Yes Attrition Counts")



CS2YesAttrition %>% ggplot(mapping = aes(x = Over18, fill = Over18)) + geom_bar() + coord_polar() + ggtitle("Polar Bar Chart of Over 18 - Yes Attrition Counts")



```






```{r}

# Graphs of Percent of Yes Attrition by Contributing Numeric-type Factors 



# Percent AGE Bar graph



CS2YesAttritselect %>% 
  count(Age) %>% 
  mutate(prop = n/sum(n)) %>% 
  ggplot(aes(x = Age, y = prop)) +
  geom_col(fill = "#FF7F24") +
  geom_text(aes(label = percent(prop)), vjust = -1) + ggtitle("Percent of Age in YES Attrition") +
  coord_cartesian(clip = "off") +
  scale_y_continuous(labels = percent_format()) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle=45, hjust=1, vjust = 1),
        axis.title = element_blank())



# Percent DistanceFromHome Bar graph
  
  
  CS2YesAttritselect %>% 
    count(DistanceFromHome) %>% 
    mutate(prop = n/sum(n)) %>% 
    ggplot(aes(x = DistanceFromHome, y = prop)) +
    geom_col(fill = "deepskyblue") +
    geom_text(aes(label = percent(prop)), vjust = -1) + ggtitle("Percent of DistanceFromHome in YES Attrition") +
    coord_cartesian(clip = "off") +
    scale_y_continuous(labels = percent_format()) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle=45, hjust=1, vjust = 1),
        axis.title = element_blank())


# Percent EnvironmentSatisfaction Bar graph
  
  
  CS2YesAttritselect %>% 
    count(EnvironmentSatisfaction) %>% 
    mutate(prop = n/sum(n)) %>% 
    ggplot(aes(x = EnvironmentSatisfaction, y = prop)) +
    geom_col(fill = "darkviolet") +
    geom_text(aes(label = percent(prop)), vjust = -1) + ggtitle("Percent of EnvironmentSatisfaction in YES Attrition") +
    coord_cartesian(clip = "off") +
    scale_y_continuous(labels = percent_format()) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle=45, hjust=1, vjust = 1),
        axis.title = element_blank())





  
# Percent HourlyRate Bar graph
  
  
  CS2YesAttritselect %>% 
    count(HourlyRate) %>% 
    mutate(prop = n/sum(n)) %>% 
    ggplot(aes(x = HourlyRate, y = prop)) +
    geom_col(fill = "yellow") +
    geom_text(aes(label = percent(prop)), vjust = -1) + ggtitle("Percent of HourlyRate in YES Attrition") +
    coord_cartesian(clip = "off") +
    scale_y_continuous(labels = percent_format()) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle=45, hjust=1, vjust = 1),
        axis.title = element_blank())
  
  

# Percent JobSatisfaction Bar graph
  
  
  CS2YesAttritselect %>% 
    count(JobSatisfaction) %>% 
    mutate(prop = n/sum(n)) %>% 
    ggplot(aes(x = JobSatisfaction, y = prop)) +
    geom_col(fill = "red") +
    geom_text(aes(label = percent(prop)), vjust = -1) + ggtitle("Percent of JobSatisfaction in YES Attrition") +
    coord_cartesian(clip = "off") +
    scale_y_continuous(labels = percent_format()) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle=45, hjust=1, vjust = 1),
        axis.title = element_blank())



# Percent Education Bar graph
  
  
  CS2YesAttritselect %>% 
    count(Education) %>% 
    mutate(prop = n/sum(n)) %>% 
    ggplot(aes(x = Education, y = prop)) +
    geom_col(fill = "springgreen") +
    geom_text(aes(label = percent(prop)), vjust = -1) + ggtitle("Percent of Education in YES Attrition") +
    coord_cartesian(clip = "off") +
    scale_y_continuous(labels = percent_format()) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle=45, hjust=1, vjust = 1),
        axis.title = element_blank())




# Percent JobInvolvement Bar graph
  
  
  CS2YesAttritselect %>% 
    count(JobInvolvement) %>% 
    mutate(prop = n/sum(n)) %>% 
    ggplot(aes(x = JobInvolvement, y = prop)) +
    geom_col(fill = "cyan") +
    geom_text(aes(label = percent(prop)), vjust = -1) + ggtitle("Percent of JobInvolvement in YES Attrition") +
    coord_cartesian(clip = "off") +
    scale_y_continuous(labels = percent_format()) +
    theme_minimal() +
   theme(axis.text.x = element_text(angle=45, hjust=1, vjust = 1),
        axis.title = element_blank())
  
  
  
  
  
# Percent JobLevel Bar graph
  
  
  CS2YesAttritselect %>% 
    count(JobLevel) %>% 
    mutate(prop = n/sum(n)) %>% 
    ggplot(aes(x = JobLevel, y = prop)) +
    geom_col(fill = "#067191") +
    geom_text(aes(label = percent(prop)), vjust = -1) + ggtitle("Percent of JobLevel in YES Attrition") +
    coord_cartesian(clip = "off") +
    scale_y_continuous(labels = percent_format()) +
    theme_minimal() +
   theme(axis.text.x = element_text(angle=45, hjust=1, vjust = 1),
        axis.title = element_blank())
  
  
  
# Percent NumCompaniesWorked Bar graph
  
  
  CS2YesAttritselect %>% 
    count(NumCompaniesWorked) %>% 
    mutate(prop = n/sum(n)) %>% 
    ggplot(aes(x = NumCompaniesWorked, y = prop)) +
    geom_col(fill = "#F0BF1D") +
    geom_text(aes(label = percent(prop)), vjust = -1) + ggtitle("Percent of NumCompaniesWorked in YES Attrition") +
    coord_cartesian(clip = "off") +
    scale_y_continuous(labels = percent_format()) +
    theme_minimal() +
   theme(axis.text.x = element_text(angle=45, hjust=1, vjust = 1),
        axis.title = element_blank())
  
  
# Percent RelationshipSatisfaction Bar graph
  
  
  
  CS2YesAttritselect %>% 
    count(RelationshipSatisfaction) %>% 
    mutate(prop = n/sum(n)) %>% 
    ggplot(aes(x = RelationshipSatisfaction, y = prop)) +
    geom_col(fill = "#DFFF00") +
    geom_text(aes(label = percent(prop)), vjust = -1) + ggtitle("Percent of RelationshipSatisfaction in YES Attrition") +
    coord_cartesian(clip = "off") +
    scale_y_continuous(labels = percent_format()) +
    theme_minimal() +
  theme(axis.text.x = element_text(angle=45, hjust=1, vjust = 1),
        axis.title = element_blank())
  
  
# Percent YearsWithCurrManager Bar graph 
  
  CS2YesAttritselect %>% 
    count(YearsWithCurrManager) %>% 
    mutate(prop = n/sum(n)) %>% 
    ggplot(aes(x = YearsWithCurrManager, y = prop)) +
    geom_col(fill = "#DE3163") +
    geom_text(aes(label = percent(prop)), vjust = -1) + ggtitle("Percent of YearsWithCurrManager in YES Attrition") +
    coord_cartesian(clip = "off") +
    scale_y_continuous(labels = percent_format()) +
    theme_minimal() +
   theme(axis.text.x = element_text(angle=45, hjust=1, vjust = 1),
        axis.title = element_blank())
  
# Percent WorkLifeBalance Bar graph
  
  
  CS2YesAttritselect %>% 
    count(WorkLifeBalance) %>% 
    mutate(prop = n/sum(n)) %>% 
    ggplot(aes(x = WorkLifeBalance, y = prop)) +
    geom_col(fill = "#e3740c") +
    geom_text(aes(label = percent(prop)), vjust = -1) + ggtitle("Percent of WorkLifeBalance in YES Attrition") +
    coord_cartesian(clip = "off") +
    scale_y_continuous(labels = percent_format()) +
    theme_minimal() +
   theme(axis.text.x = element_text(angle=45, hjust=1, vjust = 1),
        axis.title = element_blank())
  
# Percent YearsInCurrentRole Bar graph
 
  CS2YesAttritselect %>% 
    count(YearsInCurrentRole) %>% 
    mutate(prop = n/sum(n)) %>% 
    ggplot(aes(x = YearsInCurrentRole, y = prop)) +
    geom_col(fill = "#CCCCFF") +
    geom_text(aes(label = percent(prop)), vjust = -1) + ggtitle("Percent of YearsInCurrentRole in YES Attrition") +
    coord_cartesian(clip = "off") +
    scale_y_continuous(labels = percent_format()) +
    theme_minimal() +
   theme(axis.text.x = element_text(angle=45, hjust=1, vjust = 1),
        axis.title = element_blank())
  
# Percent YearsAtCompany Bar graph
  
  
  CS2YesAttritselect %>% 
    count(YearsAtCompany) %>% 
    mutate(prop = n/sum(n)) %>% 
    ggplot(aes(x = YearsAtCompany, y = prop)) +
    geom_col(fill = "#26af1c") +
    geom_text(aes(label = percent(prop)), vjust = -1) + ggtitle("Percent of YearsAtCompany in YES Attrition") +
    coord_cartesian(clip = "off") +
    scale_y_continuous(labels = percent_format()) +
    theme_minimal() +
   theme(axis.text.x = element_text(angle=45, hjust=1, vjust = 1),
        axis.title = element_blank())
  
  
# Percent StockOptionLevel Bar graph
  
  
  CS2YesAttritselect %>% 
    count(StockOptionLevel) %>% 
    mutate(prop = n/sum(n)) %>% 
    ggplot(aes(x = StockOptionLevel, y = prop)) +
    geom_col(fill = "#1e5dfa") +
    geom_text(aes(label = percent(prop)), vjust = -1) + ggtitle("Percent of StockOptionLevel in YES Attrition") +
    coord_cartesian(clip = "off") +
    scale_y_continuous(labels = percent_format()) +
    theme_minimal() +
   theme(axis.text.x = element_text(angle=45, hjust=1, vjust = 1),
        axis.title = element_blank())
  
  
# Percent PercentSalaryHike Bar graph
  
  
  CS2YesAttritselect %>% 
    count(PercentSalaryHike) %>% 
    mutate(prop = n/sum(n)) %>% 
    ggplot(aes(x = PercentSalaryHike, y = prop)) +
    geom_col(fill = "#fa1eb1") +
    geom_text(aes(label = percent(prop)), vjust = -1) + ggtitle("Percent of PercentSalaryHike in YES Attrition") +
    coord_cartesian(clip = "off") +
    scale_y_continuous(labels = percent_format()) +
    theme_minimal() +
   theme(axis.text.x = element_text(angle=45, hjust=1, vjust = 1),
        axis.title = element_blank())
  
  
  
# Percent PerformanceRating Bar graph
  
  
  CS2YesAttritselect %>% 
    count(PerformanceRating) %>% 
    mutate(prop = n/sum(n)) %>% 
    ggplot(aes(x = PerformanceRating, y = prop)) +
    geom_col(fill = "#f7fb06") +
    geom_text(aes(label = percent(prop)), vjust = -1) + ggtitle("Percent of Performance Rating in YES Attrition") +
    coord_cartesian(clip = "off") +
    scale_y_continuous(labels = percent_format()) +
    theme_minimal() +
   theme(axis.text.x = element_text(angle=45, hjust=1, vjust = 1),
        axis.title = element_blank())
  
  
 
  
  
# Percent TotalWorkingYears Bar graph
  
  
  CS2YesAttritselect %>% 
    count(TotalWorkingYears) %>% 
    mutate(prop = n/sum(n)) %>% 
    ggplot(aes(x = TotalWorkingYears, y = prop)) +
    geom_col(fill = "#56116b") +
    geom_text(aes(label = percent(prop)), vjust = -1) + ggtitle("Percent of TotalWorkingYears in YES Attrition") +
    coord_cartesian(clip = "off") +
    scale_y_continuous(labels = percent_format()) +
    theme_minimal() +
   theme(axis.text.x = element_text(angle=45, hjust=1, vjust = 1),
        axis.title = element_blank())
  
  
  
  
  
# Percent TrainingTimesLastYear Bar graph
  
  
  CS2YesAttritselect %>% 
    count(TrainingTimesLastYear) %>% 
    mutate(prop = n/sum(n)) %>% 
    ggplot(aes(x = TrainingTimesLastYear, y = prop)) +
    geom_col(fill = "#2cdf20") +
    geom_text(aes(label = percent(prop)), vjust = -1) + ggtitle("Percent of TrainingTimesLastYear in YES Attrition") +
    coord_cartesian(clip = "off") +
    scale_y_continuous(labels = percent_format()) +
    theme_minimal() +
   theme(axis.text.x = element_text(angle=45, hjust=1, vjust = 1),
        axis.title = element_blank())
  
  
  
  
  
# Percent YearsSinceLastPromotion Bar graph
  
  
  CS2YesAttritselect %>% 
    count(YearsSinceLastPromotion) %>% 
    mutate(prop = n/sum(n)) %>% 
    ggplot(aes(x = YearsSinceLastPromotion, y = prop)) +
    geom_col(fill = "#df2049") +
    geom_text(aes(label = percent(prop)), vjust = -1) + ggtitle("Percent of YearsSinceLastPromotion in YES Attrition") +
    coord_cartesian(clip = "off") +
    scale_y_continuous(labels = percent_format()) +
    theme_minimal() +
   theme(axis.text.x = element_text(angle=45, hjust=1, vjust = 1),
        axis.title = element_blank())
  
```  
  
  
  
  
 
```{r} 
 
# comparison 3D graph with the Top Three Factors contributing to Attrition

library(plotly)


p <- plot_ly(CaseStudy2-data, x = ~WorkLifeBalance, y = ~StockOptionLevel, z = ~JobLevel, color = ~Attrition) %>%
  add_markers() %>%
  layout(scene = list(xaxis = list(title = 'PercentPerformanceRating'),
                      yaxis = list(title = 'StockOptionLevel'),
                      zaxis = list(title = 'JobLevel')))
p
 
 
```
 
 
  
```{r}
  
# KNN Classification is inadequate not enough data to predict a yes Attrition

view(CaseStudy2-data)

  CS2AttritselectKNN <- CaseStudy2-data %>% select(Attrition, Age, DistanceFromHome, EnvironmentSatisfaction, HourlyRate, JobSatisfaction, Education, DailyRate, JobInvolvement, MonthlyIncome, JobLevel, MonthlyRate, NumCompaniesWorked, PercentSalaryHike, PerformanceRating, EmployeeCount, RelationshipSatisfaction, YearsWithCurrManager,WorkLifeBalance, YearsInCurrentRole, StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear, YearsAtCompany, YearsSinceLastPromotion)
  
  
  view(CS2AttritselectKNN)
  view(CaseStudy2CompSet_No_Attrition)
  

  
# KNN model numbers only

set.seed(1)
iterations = 500
numks = 90
splitPerc = .70

masterAcc = matrix(nrow = iterations, ncol = numks)

for(j in 1:iterations)
{
  trainIndices = sample(1:dim(CS2AttritselectKNN )[1],round(splitPerc * dim(CS2AttritselectKNN )[1]))
  train = CS2AttritselectKNN [trainIndices,]
  test = CS2AttritselectKNN [-trainIndices,]
  for(i in 1:numks)
  {
    classifications = knn(train[,c(11,15,21)],test[,c(11,15,21)],train$Attrition, prob = TRUE, k = i)
    table(classifications,test$Attrition)
    CM = confusionMatrix(table(classifications,test$Attrition))
    masterAcc[j,i] = CM$overall[1]
  }
  
}

MeanAcc = colMeans(masterAcc)

plot(seq(1,numks,1),MeanAcc, type = "l")    


df = CaseStudy2CompSet_No_Attrition[,c(15,25,28)]
Case2PredictionsKNNnum_Bowerman_Attrition <- knn(CaseStudy2-data[,c(16,26,29)], df, CaseStudy2-data$Attrition, k = 30, prob = TRUE)

head(Case2PredictionsKNNnum_Bowerman_Attrition)




write.csv(Case2PredictionsKNN_Bowerman_Attrition,"H:/Schools/SMU/DoingDataScienceHomework/UnitOne/Unit One/Unit 14 and 15 Case Study 2/Case2PredictionsKNNnum_Bowerman_Attrition.csv", row.names = TRUE)

```

```{r}



# KNN Classification is inadequate not enough data to predict a yes Attrition

view(CaseStudy2-data)

  CS2AttritselectKNN <- CaseStudy2-data %>% select(Attrition, Age, DistanceFromHome, EnvironmentSatisfaction, HourlyRate, JobSatisfaction, Education, DailyRate, JobInvolvement, MonthlyIncome, JobLevel, MonthlyRate, NumCompaniesWorked, PercentSalaryHike, PerformanceRating, EmployeeCount, RelationshipSatisfaction, YearsWithCurrManager,WorkLifeBalance, YearsInCurrentRole, StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear, YearsAtCompany, YearsSinceLastPromotion)
  
  
  view(CS2AttritselectKNN)
  view(CaseStudy2CompSet_No_Attrition)
  

# KNN model All factors included

set.seed(1)
iterations = 500
numks = 90
splitPerc = .70

masterAcc = matrix(nrow = iterations, ncol = numks)

for(j in 1:iterations)
{
  trainIndices = sample(1:dim(CaseStudy2-data)[1],round(splitPerc * dim(CaseStudy2-data)[1]))
  train = CaseStudy2-data [trainIndices,]
  test = CaseStudy2-data [-trainIndices,]
  for(i in 1:numks)
  {
    classifications = knn(train[,c(16,26,29)],test[,c(16,26,29)],train$Attrition, prob = TRUE, k = i)
    table(classifications,test$Attrition)
    CM = confusionMatrix(table(classifications,test$Attrition))
    masterAcc[j,i] = CM$overall[1]
  }
  
}

MeanAcc = colMeans(masterAcc)

plot(seq(1,numks,1),MeanAcc, type = "l")    



df = CaseStudy2CompSet_No_Attrition[,c(15,25,28)]
Case2PredictionsKNN_Bowerman_Attrition <- knn(CaseStudy2-data[,c(16,26,29)], df, CaseStudy2-data$Attrition, k = 30, prob = TRUE)

Case2PredictionsKNNID_Bowerman_Attrition <- cbind(Case2PredictionsKNN_Bowerman_Attrition, ID = CaseStudy2CompSet_No_Attrition$ID)  


head(Case2PredictionsKNNID_Bowerman_Attrition)





write.csv(Case2PredictionsKNNID_Bowerman_Attrition,"H:/Schools/SMU/DoingDataScienceHomework/UnitOne/Unit One/Unit 14 and 15 Case Study 2/Case2Predictions_Bowerman_KNN_Attrition.csv", row.names = TRUE)


```




```{r}



# naiveBayes Classification of CaseStudy2data 



model = naiveBayes(Attrition~.,data = CaseStudy2-data)
predict(model,CaseStudy2-data[,c(2,5,7,8,12,14,15,16,18,22,25,26,27,29:36)])

df = CaseStudy2CompSet_No_Attrition[,c(2,4,6,7,11,13,14,15,17,21,24,25,26,28:35)]
predict(model,df) #just classifications
CaseStudy2CompSetLabeled <- predict(model,df, type = "raw") #gives probabilities #type = "raw"



CaseStudy2CompSetLabeledIDd <- cbind(CaseStudy2CompSetLabeled, ID = CaseStudy2CompSet_No_Attrition$ID)  


view(CaseStudy2CompSetLabeledIDd)


write.csv(CaseStudy2CompSetLabeledIDd,"H:/Schools/SMU/DoingDataScienceHomework/UnitOne/Unit One/Unit 14 and 15 Case Study 2/CaseStudy2PredictionsBowerman_NB_Attrition.csv", row.names = TRUE)


```

c(15,25,28)



```{r}

# Trying Random Forest Classification for the data:


library(randomForest)
library(caTools)


head(CaseStudy2-data)

summary(CaseStudy2-data)

sapply(CaseStudy2-data, class)


CaseStudy2-data <- transform(
  CaseStudy2-data,
  Department=as.factor(Department),
  JobRole=as.factor(JobRole),
  Attrition=as.factor(Attrition),
  Gender=as.factor(Gender),
  Over18=as.factor(Over18),
  BusinessTravel=as.factor(BusinessTravel),
  EducationField=as.factor(EducationField),
  MaritalStatus=as.factor(MaritalStatus),
  OverTime=as.factor(OverTime)
  
)


CaseStudy2CompSet_No_Attrition <- transform(
  CaseStudy2CompSet_No_Attrition,
  Department=as.factor(Department),
  JobRole=as.factor(JobRole),
  Gender=as.factor(Gender),
  Over18=as.factor(Over18),
  BusinessTravel=as.factor(BusinessTravel),
  EducationField=as.factor(EducationField),
  MaritalStatus=as.factor(MaritalStatus),
  OverTime=as.factor(OverTime)
  
)


head(CaseStudy2CompSet_No_Attrition)

head(CaseStudy2-data)
summary(CaseStudy2-data)


# sample = sample.split(CaseStudy2-data$Attrition, SplitRatio = 0.75)
# train = subset(CaseStudy2-data, sample == TRUE)
# test  = subset(CaseStudy2-data, sample == FALSE)
# dim(train)
# dim(test)


train = CaseStudy2-data
test = CaseStudy2CompSet_No_Attrition


dim(train)
dim(test)


CaseStudy2_rf <- randomForest(Attrition ~ .,data=train)



pred = predict(CaseStudy2_rf, newdata=test)

CaseStudy2CompSet_RF_Labeled <- cbind(pred, ID = CaseStudy2CompSet_No_Attrition$ID)  


view(CaseStudy2CompSet_RF_Labeled)


write.csv(CaseStudy2CompSet_RF_Labeled,"H:/Schools/SMU/DoingDataScienceHomework/UnitOne/Unit One/Unit 14 and 15 Case Study 2/CaseStudy2PredictionsBowerman_RF_Attrition.csv", row.names = TRUE)





```




```{r}

#   linear plots of Contributing Factors vs. Monthly Income



library(reshape2)



CaseStudy2-data %>% 
  ggplot(aes(x = Age, y = MonthlyIncome)) + geom_point() + 
  ggtitle("CaseStudy2-data: Age v. MonthlyIncome") + geom_smooth(method = "lm")



CaseStudy2-data %>% 
  ggplot(aes(x = JobRole, y = MonthlyIncome)) + geom_point() + 
  ggtitle("CaseStudy2-data: Job Role v. MonthlyIncome") + geom_smooth(method = "lm")
  


CaseStudy2-data %>% 
  ggplot(aes(x = JobLevel, y = MonthlyIncome)) + geom_point() + 
  ggtitle("CaseStudy2-data: Job Level v. MonthlyIncome") + geom_smooth(method = "lm")


#   linear Prediction model of CaseStudy2CompSet for Salary



fit = lm(MonthlyIncome~JobRole + JobLevel + Age, data = CaseStudy2-data)
summary(fit)

preds = predict(fit, newdata = CaseStudy2CompSet_No_Salary)
preds
CaseStudy2Predictions_Salary <- preds


CaseStudy2Predictions_Bowerman_Salary <- cbind(CaseStudy2Predictions_Salary, CaseStudy2CompSet_No_Salary$ID)


view(CaseStudy2Predictions_Bowerman_Salary)


write.csv(CaseStudy2Predictions_Bowerman_Salary,"H:/Schools/SMU/DoingDataScienceHomework/UnitOne/Unit One/Unit 14 and 15 Case Study 2/CaseStudy2Predictions_Bowerman_Salary.csv", row.names = TRUE)


```
